### ISSUE TITLE
Windows release binaries being mis-detected as malicious by VirusTotal

### ISSUE THREAD

**Issue by Kneesnap** [0x09/jbfinspect#1] opened 2022-09-21 02:51 UTC
The most recent release (at minimum: [jbfinspect-w32-x86_64.exe](https://github.com/0x09/jbfinspect/releases/download/v1.0/jbfinspect-w32-x86_64.exe)) appears to be infected with malware.

According to [VirusTotal](https://www.virustotal.com/gui/file/f16ce5c99912cb0f2dd4b7c3b6e7f015f4735e314cd4ae2af1374272ceef69bf/detection), the executable connects to [23.216.147.64](https://www.virustotal.com/gui/ip-address/23.216.147.64) and downloads an executable file.
Additionally, it seems to think the executable has been tampered.

Assuming good faith here and that the author did not intend for the infection, and is just instead infected themselves.

**Comment by mwojo** [comment] 2022-09-21 03:43
Hi @Kneesnap 

Thanks for reporting this. I'm traveling atm and can't confirm if this is a false positive or not, but I'm removing the Windows binaries until I can.

**Comment by mwojo** [comment] 2022-09-21 03:55
Hi @Kneesnap 

Thanks for reporting this. I'm traveling atm and can't confirm whether this is a false positive or not, but I've removed the windows binaries in the mean time.

**Comment by 0x09** [comment] 2022-09-21 04:02
(Sorry for the 3x spam, keep switching to work.)

Hi @Kneesnap 

Thanks for reporting this. I’m traveling atm and can’t confirm whether this is a false positive or not (there absolutely should not be any internet traffic from these binaries, so it sounds like not.) I’ve removed the windows binaries in the mean time.

**Comment by 0x09** [comment] 2022-09-21 04:39
On looking into this a bit further, I’m unable to find any references to the detected trojan prior to 2020 — whereas the windows binaries released here were built back in 2016 and haven’t been updated since. This particular trojan also appears to be a common false positive result.
As mentioned, I’ll definitely analyze these in depth when I’m back at my computer but it seems this does warrant a bit more looking into and these were possibly not affected after all. Regardless thanks again for bringing it to my attention.

**Comment by Kneesnap** [comment] 2022-09-21 08:59
No problem! VirusTotal makes it seem like it's doing a network connection, and querying system information. It could be a false positive, but that seems pretty indicative of bad behavior if it is true. But, who knows Virus Total could be getting confused by something else.

In the meantime, I will just use this in a VM.

**Comment by 0x09** [comment] 2022-09-23 05:52
I noticed a number of other questions about this same result and IP from VirusTotal, e.g.
* https://learn.microsoft.com/en-us/answers/questions/832664/c-app-flagged-in-virus-total-34contacted-ip-addres.html
* https://stackoverflow.com/questions/73820429/executable-compiled-by-gcc-is-seen-as-a-virus-by-13-detectors-on-virustotal-and
* https://stackoverflow.com/questions/72073639/c-sharp-app-flagged-in-virus-total-contacted-ip-addresses-dont-know-why
* https://www.reddit.com/r/antivirus/comments/urvf44/is_this_file_safe/

Which point out that this is an Akami IP commonly used by Microsoft and imply that it may be an issue with VirusTotal's sandbox.

Decompilation on the binary shows no networking functions and only 6 calls in total to `_write`/`fwrite` (which is expected as that's exactly the number we call for writing out thumbnails, plus MinGW's printf implementation -- but I don't see any evidence of e.g. copying a file fetched over the network to disk as VT reports).
Neither the integer nor dot form of the IP named by VirusTotal appear in the binary at all (though that could be obfuscated.)

I'll reach out to VirusTotal for clarification on the result here.

Edit to add, neither opswat nor Avira report infection:
https://metadefender.opswat.com/results/file/bzIyMDkyM2pERWtxd3Z6cE9IeHdMQ0FjNTlX/regular/overview
 
Even if this is entirely bogus on VirusTotal's part though I would like to add binaries for other projects down the line and it'd never have occurred to me to check if online scanners reported negatively about them, so it's really handy to know about this.

**Comment by Kneesnap** [comment] 2022-09-23 17:02
Oh, that's very nice to hear. Thanks for the effort looking into this!

**Comment by 0x09** [comment] 2022-09-23 22:53
I've reattached the mentioned binaries to the release after receiving the following response from a support person at VirusTotal:

> It looks like the Microsoft sys-internal sandbox VM is generating the connection [contacted IPs] and not related to the sample itself. 
>
> We'll reach out to them to see about filtering this in the future. 

I've requested permission to post the actual email thread here, though I have a feeling they may not respond to this.

Being unfamiliar with Windows malware for the most part and given that these were built quite a long time ago I wanted to err on the side of caution here (e.g. if it was possible the build machine I was using in 2016 was somehow able to infect exes compiled on it). But since
1) Decompilation provides no evidence that these were modified
2) The one antivirus engine ([MaxSecure](https://www.maxpcsecure.com)) out of 71 that VT uses flagged a trojan which first appeared ~4 years after this release
3) The network connections to Akami and Microsoft flagged [here](https://www.virustotal.com/gui/file/f16ce5c99912cb0f2dd4b7c3b6e7f015f4735e314cd4ae2af1374272ceef69bf/relations) were not actually from jbfinspect

I'm no longer concerned about including them in the release.

As mentioned I'll definitely keep this in mind if I build binary releases for any projects in the future to get ahead of any false positives, so appreciate pointing this out.

I'll update the title accordingly and close this unless you have any other concerns @Kneesnap

**Comment by 0x09** [comment] 2022-09-24 00:28
Also for reference, attaching a debug build from the same release, since this makes it much easier to poke through the decompilation and verify that everything being called is either from mingw, the MS C runtime or the jbfinspect code itself.
[jbfinspect-w32-x86_64-debug.exe.zip](https://github.com/0x09/jbfinspect/files/9637565/jbfinspect-w32-x86_64-debug.exe.zip)

The only difference between this and the release binary is the inclusion of debug symbols (confirmed via disassembly.)

**Comment by 0x09** [comment] 2022-09-26 02:07
An additional update to this: I spent some time seeing if I could track down the version of GCC used to create the original build reported and reproduce it. It turns out the supposedly malicious issues flagged in the initial VirusTotal report can be reproduced simply by compiling [the current source code](https://github.com/0x09/jbfinspect/blob/196d61560ce990b4741b646618c3ce53d06fc400/jbfinspect.c) with [GCC 5.3.0 from MinGW-w64](https://community.chocolatey.org/packages/mingw/5.3.0), the closest available version to the one used for the original build, as well as any other GCC version up to 7.3.

```
choco install -y mingw --version=5.3.0
C:\tools\mingw64\bin\gcc.exe -O2 -o jbfinspect-gcc-5.3.0-O2.exe jbfinspect.c
```

Uploading the resulting binary `jbfinspect-gcc-5.3.0-O2.exe` to VirusTotal results in the following: https://www.virustotal.com/gui/file/a07fede7ce87805357c1928ff280b75f5114b98db237e73b434ef8f1fabc8af0/
Which, with the exception of the YomiHunter sandbox which [wasn't used for this upload](https://www.virustotal.com/gui/file/a07fede7ce87805357c1928ff280b75f5114b98db237e73b434ef8f1fabc8af0/behavior) for some reason, reports all issues present in the [original report](https://www.virustotal.com/gui/file/f16ce5c99912cb0f2dd4b7c3b6e7f015f4735e314cd4ae2af1374272ceef69bf/detection).

I tried the above build using these two Vagrant boxes with the same result:
[devopsgroup-io/windows_server-2012r2-standard-amd64-nocm](https://app.vagrantup.com/devopsgroup-io/boxes/windows_server-2012r2-standard-amd64-nocm/versions/0.0.1)
[gusztavvargadr/windows-10](https://app.vagrantup.com/gusztavvargadr/boxes/windows-10)

Since YomiHunter wasn't used for this upload, I submitted the binary directly to https://yomi.yoroi.company/submissions (can be seen [here](https://yomi.yoroi.company/submissions/public)) and am waiting for the results which apparently take awhile.

**Comment by 0x09** [comment] 2022-09-29 03:19
> Which, with the exception of the YomiHunter sandbox which [wasn't used for this upload](https://www.virustotal.com/gui/file/a07fede7ce87805357c1928ff280b75f5114b98db237e73b434ef8f1fabc8af0/behavior) for some reason, reports all issues present in the [original report](https://www.virustotal.com/gui/file/f16ce5c99912cb0f2dd4b7c3b6e7f015f4735e314cd4ae2af1374272ceef69bf/detection).

YomiHunter analysis for the freshly compiled exe has finally finished today, it is positive ("malscore" 10, the highest possible), which is the same as the original report:
https://yomi.yoroi.company/report/6330f89123e36262c5f45411/63342094205b1e1e23ccfef1/overview

All this is to say that compiling the source code today, without modification, with a similar version of GCC causes all of the same alleged malware as flagged in the original report for the release binary. This can be independently verified, even ignoring the things mentioned earlier that indicate these were false positives on VirusTotal's side.

This was maybe over the top just to demonstrate that these were false positives, which apparently happen quite often with software compiled with MinGW or Msys2 GCC, but I'd rather be thorough about something like this, especially since the release was quite old at this point and the original build environment no longer available.

LMK if you have any other thoughts about this @Kneesnap, but given the above I don't see any way that the scan result could be accurate.

**Comment by Kneesnap** [comment] 2022-09-29 17:40
Seems pretty thorough to me, I think the evidence does suggest a false
positive yeah.

**Comment by Kneesnap** [comment] 2022-10-11 06:59
No other concerns, this addresses everything by the looks of it.

**Comment by 0x09** [comment] 2022-10-11 22:14
Thanks, I realized also while looking into this that the last release predated [this bug fix](https://github.com/0x09/jbfinspect/commit/196d61560ce990b4741b646618c3ce53d06fc400) so I'll publish a new one shortly. More recent versions of MinGW/GCC don't seem to have the reported issue, so I'll just keep this issue open until the new release is up.

**Comment by 0x09** [comment] 2022-10-21 02:42
New release published: https://github.com/0x09/jbfinspect/releases/tag/v2.0.0

While the win32-x86_64 binary is [marked clean](https://www.virustotal.com/gui/file/2ee7bc0bad592a6a431a01758adfd42df77f65e2e723af2932a1d89a84a4c1bb?nocache=1) by virustotal, the win32-i686 release now produces [2 malicious reports](https://www.virustotal.com/gui/file/300e3d034bbe2fd653b088a0cab5f1576c4ea88c681eaf315ce1e786f97ee1f3/detection) different from the ones highlighted in this issue.

I've included a Vagrantfile in the release defining the build environment used and the steps to build the binaries in it so that these results can be reproduced from the source code independently.

I'd like to see if those two vendors accept submissions for false positives, but since it's at least possible to confirm these as such -- which was my biggest concern with this issue -- I'll close it with that.

Thanks again for reporting, it's been helpful to reconsider what kind of build information is useful to include with these releases for future reference and to scope out these sorts of reports beforehand.

**Closed as completed by 0x09** 2022-10-21 02:42 UTC
